### ISSUE TITLE
Running Xelmish on androi

### ISSUE THREAD

**Issue by kaeedo** [ChrisPritchard/Xelmish#7]
Is it possible to run a Xelmish game on android?

I assume yes, but my attempts so far have not gotten anywhere near successful.

**Comment by ChrisPritchard** [comment]
Hi @kaeedo! I would assume not, since Xelmish is built using dotnet core and dotnet core does not compile on Android.

That being said, I am sure you could do something crazy hacky to get it running but I have not tried; if you want to have a go, this repo looks like a good first step: https://github.com/qmfrederik/coredroid
